### ISSUE TITLE
Automatically set up import map override for react / react dom

### ISSUE THREAD

**Issue by joeldenning** [single-spa/single-spa-playground#18]
Create-single-spa users should not have to manually create overrides for react, react-dom, Vue, Vue-router, etc when testing out their new repo.

**Comment by TheMcMurder** [comment]
Are you thinking to just put all of those in the import map, Or allow configuration somehow?

**Comment by joeldenning** [comment]
I think just throwing a bunch of dependencies into the import map below might be fine. Other option would be to provide a query param to the `instant-test` route, but I don't think that provides much value over just always having it there:

https://github.com/single-spa/single-spa-playground/blob/5449e5c5b8319cc7c43bdcbfb7a2178163ba315e/index.html#L13-L20

**Comment by joeldenning** [comment]
Resolved in https://github.com/single-spa/single-spa-playground/pull/21
