### ISSUE TITLE
Error: Could not download app -- server didn't respond with javascript code, but with 'text/html'

### ISSUE THREAD

**Issue by horlabyc** [single-spa/single-spa-playground#42]
Hi, I am trying to create a new single-spa application following the documentation. I followed all steps till the point where I need to validate the app in the playgroud. I keep getting the above error. What could be wrong please?

**Comment by horlabyc** [comment]
The app is running locally on port 4200. When I entered http://localhost:4200/main.js in the browser, i can get the js files. However, the app verification on the playground could not get the files

**Comment by filoxo** [comment]
- How did you create this application?
- Can you try clearing the browser cache for single-spa-playground?
- Are you able to share a repo where this is happening?

**Comment by filoxo** [comment]
@horlabyc were you able to find a solution to your issue?

**Comment by horlabyc** [comment]
@filoxo I have not found a solution. However I stopped working with the playground app. It worked fine when I served the applications locally but I could not get it verified on the Playgroud app.

The app was created using **create-single-spa** from the cli by the way

**Comment by filoxo** [comment]
Glad you were able to work around that. There isn't enough details for us to be able to triage the problem but if you're not blocked I not going to spend the extra time to investigate. Feel free to open new issues as you encounter them.
