### ISSUE TITLE
http://localhost:9000/assets/i18n/en.json giving 404 in Angular Single SPA app

### ISSUE THREAD

**Issue by rajiv687** [single-spa/single-spa-playground#48]
Hi , 
I have create MFE and integrated inside single spa however getting 404  error
Request URL: http://localhost:9000/assets/i18n/en.json
Request Method: GET
Status Code: 404 Not Found
Remote Address: [::1]:9000
Referrer Policy: strict-origin-when-cross-origin
![image](https://user-images.githubusercontent.com/17966722/184859171-e91b8431-2613-44d6-a3ce-7e4de8da9112.png)

:

FYI :I installed all libraries related i18n inside single spa  .
Same application running fine when I run simply on Angular app. Kindly let me know where I am wrong on priority .

**Comment by filoxo** [comment]
Relative URLs are _relative to the origin document_ and not to the javascript asset that requested it. Please review the single-spa-angular documentation for additional information: https://single-spa.js.org/docs/ecosystem-angular#angular-assets
