### ISSUE TITLE
when i run my root config in the browser after buildinig the rooot config it showing cannot use import statement outside a module .

### ISSUE THREAD

**Issue by donexfience** [single-spa/single-spa-playground#65]
I started by typing create-single-spa --moduleType root-config . and i created the root config boiler plate code that is autmotically generated by the single spa . When i started the file it showing the error . when i click that error it showing the js file of the root config in the dist folder. the dist folder has the import statement int the first file it showing the error there . I will attach my git hub link of that file . Can you please check it and give me a suggestio
![image](https://github.com/user-attachments/assets/897a443c-cc55-4c96-b602-9ad62cebb4d2)
![Screenshot 2024-10-10 123342](https://github.com/user-attachments/assets/0b7f9352-e12d-450c-919c-db27f942f84c)
n . Its almost 4 days im workling on it to fix the issues.[https://github.com/donexfience/MF_Testing_debug_purpose](url)

**Comment by syamswan** [comment]
I am also facing the same issue from today mrng,  have you fixed this issue bro ?

**Comment by FelipeNasci** [comment]
+1
facing same issue

**Comment by jd-wong-ujet** [comment]
Facing same issue

**Comment by donexfience** [comment]
> Facing same issue

you can downgrade the single spa version and try to install the root config
Uninstall the v5 of the cli 'create-single-spa' and install v4.1.6 and regenerate your root config 
I think they already fixed the issue because he posted on issue they fixed it have a new realease of root config generator

**Comment by joeldenning** [comment]
Local root config worked for me today. This was likely fixed in https://github.com/single-spa/create-single-spa/releases/tag/generator-single-spa%405.0.1
